# Generated by Django 4.0.5 on 2022-07-01 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_name_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fraud_weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.PositiveSmallIntegerField(default=1)),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('date', models.DateField(auto_now_add=True)),
                ('fraud_score', models.FloatField(default=0)),
                ('service_class', models.PositiveSmallIntegerField(default=1)),
                ('service_name', models.CharField(max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
            options={
                'unique_together': {('organization', 'client_number')},
            },
        ),
    ]
